# Generated by Django 5.1 on 2024-08-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_community_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.TextField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='category',
            field=models.CharField(choices=[('food', 'food'), ('lifestyle', 'lifestyle')], default='food', max_length=30),
        ),
    ]
