# Generated by Django 5.1 on 2024-08-23 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_community_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='user_id',
            new_name='user',
        ),
    ]
