# Generated by Django 5.1 on 2024-08-23 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_community_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='user',
            new_name='user_id',
        ),
    ]
