# Generated by Django 5.1 on 2024-08-23 18:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0003_hashtag_community_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('img', models.ImageField(blank=True, upload_to='community_images/')),
                ('price', models.IntegerField(blank=True)),
                ('product_name', models.TextField(max_length=50)),
                ('link', models.TextField(null=True)),
                ('people_num', models.IntegerField()),
                ('product_category', models.IntegerField(blank=True, choices=[(1, '식료품'), (2, '생필품')], null=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.hashtag')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
