# Generated by Django 5.1 on 2024-08-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobying', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobying',
            name='product_name',
            field=models.CharField(max_length=50),
        ),
    ]
