# Generated by Django 5.1 on 2024-08-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobying', '0002_alter_cobying_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cobying',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='cobying',
            name='img',
            field=models.ImageField(blank=True, upload_to='cobying_images/'),
        ),
        migrations.AlterField(
            model_name='cobying',
            name='people_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cobying',
            name='product_category',
            field=models.CharField(blank=True, choices=[('food', '식료품'), ('food', '생필품')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cobying',
            name='product_name',
            field=models.TextField(max_length=50),
        ),
    ]
